---
# Copyright (c) 2014 Lekane Oy. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#    * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#    * Neither the name of Lekane Oy nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

- name: Set cassandra_config_dir fact (DCE)
  set_fact: cassandra_config_dir=/etc/cassandra
  when: install_version == "dce"

- name: Set cassandra_config_dir fact (DSE)
  set_fact: cassandra_config_dir=/etc/dse/cassandra
  when: install_version == "dse"

- name: Set cassandra_config_dir fact (Apache)
  set_fact: cassandra_config_dir=/etc/cassandra
  when: install_version == "apache"

- name: Check for cassandra_config_dir existence
  stat: path={{ cassandra_config_dir }}
  register: cassandra_config_dir_state

- name: Create RAID-0 from ephemeral drives
  script: "raid_ephemeral.sh {{ deployment_environment }}"
  when:
    - init_server | default(false) | bool
    - deployment_environment == "aws"

- name: Symlink /ephemeral to /data
  file: src=/ephemeral dest=/data state=link
  when:
    - init_server | default(false) | bool
    - deployment_environment == "euca"

- name: Create /data directory
  file: path=/data state=directory owner=root group=root mode=0777
  when:
    - init_server | default(false) | bool
    - deployment_environment == "openstack"

- name: Stop Cassandra DCE
  shell: "nodetool disablethrift && nodetool disablebinary && nodetool disablegossip && nodetool drain && service cassandra stop"
  ignore_errors: "{{ ignore_shutdown_errors | default(false) }}"
  when:
    - not (init_server | default(false) | bool)
    - install_version == "dce"
    - cassandra_config_dir_state.stat.exists == true

- name: Stop Cassandra DSE
  shell: "nodetool disablethrift && nodetool disablebinary && nodetool disablegossip && nodetool drain && service dse stop"
  ignore_errors: "{{ ignore_shutdown_errors | default(false) }}"
  when:
    - not (init_server | default(false) | bool)
    - install_version == "dse"
    - cassandra_config_dir_state.stat.exists == true

- name: Stop Cassandra Apache
  shell: "nodetool disablethrift && nodetool disablebinary && nodetool disablegossip && nodetool drain && service cassandra stop"
  ignore_errors: "{{ ignore_shutdown_errors | default(false) }}"
  when:
    - not (init_server | default(false) | bool)
    - install_version == "apache"
    - cassandra_config_dir_state.stat.exists == true

- name: Check Cassandra system.log existence
  stat: path=/var/log/cassandra/system.log
  register: system_log_file

- name: Clear Cassandra system.log
  shell: echo > /var/log/cassandra/system.log
  when: system_log_file.stat.exists == true

- name: Install Datastax Community Cassandra & tools
  when: install_version == "dce"
  apt: pkg={{item}} state=present
  register: cassandra_installed_dce
  with_items:
  - dsc30={{ dsc_version }}
  - cassandra={{ cassandra_version }}
  - cassandra-tools={{ cassandra_tools_version }}

- name: Install Datastax Enterprise Cassandra
  when: install_version == "dse"
  register: cassandra_installed_dse
  apt: pkg={{item}} state=present
  with_items:
  - dse-full={{ dse_version }}

- name: Install Apache Cassandra
  when: install_version == "apache"
  apt: pkg={{item}} state=latest
  register: cassandra_installed_apache
  with_items:
  - cassandra
  - cassandra-tools

- name: get cassandra_installed variable (DCE)
  set_fact: cassandra_installed="{{ cassandra_installed_dce.changed }}"

- name: get cassandra_installed variable (DSE)
  set_fact: cassandra_installed="{{ cassandra_installed_dse.changed }}"

- name: get cassandra_installed variable (Apache)
  set_fact: cassandra_installed="{{ cassandra_installed_apache.changed }}"

- name: Get installed Cassandra version
  shell: "dpkg -l | grep ' cassandra ' | awk '{print $3}'"
  register: cassandra_installed_apache_version

- set_fact: cassandra_version="{{ cassandra_installed_apache_version.stdout }}"

- debug: var=cassandra_version

- name: Wait for server autostart
  wait_for: path=/var/log/cassandra/system.log search_regex="Starting listening for CQL clients"
  when:
    - init_server | default(false) | bool
    - cassandra_installed

- name: Stop Cassandra DCE (autostarted on install)
  service: name=cassandra state=stopped
  when:
    - init_server | default(false) | bool
    - install_version == "dce"

- name: Stop Cassandra DSE (autostarted on install)
  service: name=dse state=stopped
  when:
    - init_server | default(false) | bool
    - install_version == "dse"

- name: Stop Cassandra Apache (autostarted on install)
  service: name=cassandra state=stopped
  when:
    - init_server | default(false) | bool
    - install_version == "apache"

- name: Clear Cassandra logs (after autostart)
  shell: echo > /var/log/cassandra/system.log
  when:
    - init_server | default(false) | bool

- name: Cassandra system.log ownership check
  file: path=/var/log/cassandra/system.log owner=cassandra group=cassandra mode=0644

- name: Remove cluster metadata
  shell: rm -rf /var/lib/cassandra/*
  when:
    - init_server | default(false) | bool

- name: Create data directory
  file: path=/data/cassandra/data state=directory owner=cassandra group=cassandra mode=0755

- name: Create commitlog directory
  file: path=/data/cassandra/commitlog state=directory owner=cassandra group=cassandra mode=0755

- name: Create saved_caches directory
  file: path=/data/cassandra/saved_caches state=directory owner=cassandra group=cassandra mode=0755

- name: Create commitlog backup directory
  file: path=/data/cassandra/commit_log_backup state=directory owner=cassandra group=cassandra mode=0755

- name: Create hints directory
  file: path=/data/cassandra/hints state=directory owner=cassandra group=cassandra mode=0755

- name: Backup original cassandra.yaml
  command: "cp {{ cassandra_config_dir }}/cassandra.yaml {{ cassandra_config_dir }}/cassandra.yaml.{{ cassandra_version }}.bak creates={{ cassandra_config_dir }}/cassandra.yaml.{{ cassandra_version }}.bak"

- name: Backup original cassandra-env.sh
  command: "cp {{ cassandra_config_dir }}/cassandra-env.sh {{ cassandra_config_dir }}/cassandra-env.sh.{{ cassandra_version }}.bak creates={{ cassandra_config_dir }}/cassandra-env.sh.{{ cassandra_version }}.bak"

- name: Backup original cassandra-rackdc.properties
  command: "cp {{ cassandra_config_dir }}/cassandra-rackdc.properties {{ cassandra_config_dir }}/cassandra-rackdc.properties.{{ cassandra_version }}.bak creates={{ cassandra_config_dir }}/cassandra-rackdc.properties.{{ cassandra_version }}.bak"

- name: Backup original cassandra-topology.properties
  command: "cp {{ cassandra_config_dir }}/cassandra-topology.properties {{ cassandra_config_dir }}/cassandra-topology.properties.{{ cassandra_version }}.bak creates={{ cassandra_config_dir }}/cassandra-topology.properties.{{ cassandra_version }}.bak"

- name: Backup original jvm.options
  command: "cp {{ cassandra_config_dir }}/jvm.options {{ cassandra_config_dir }}/jvm.options.{{ cassandra_version }}.bak creates={{ cassandra_config_dir }}/jvm.options.{{ cassandra_version }}.bak"

- name: Template cassandra.yml
  template: "src=cassandra.yaml.j2 dest={{ cassandra_config_dir }}/cassandra.yaml mode=0664"

- name: Template cassandra-env.sh
  template: "src=cassandra-env.sh.j2 dest={{ cassandra_config_dir }}/cassandra-env.sh mode=0664"

- name: Template cassandra-rackdc.properties
  template: "src=cassandra-rackdc.properties.j2 dest={{ cassandra_config_dir }}/cassandra-rackdc.properties mode=0664"

- name: Template cassandra-topology.properties
  template: "src=cassandra-topology.properties.j2 dest={{ cassandra_config_dir }}/cassandra-topology.properties mode=0664"

- name: Template jvm.options
  template: "src=jvm.options.j2 dest={{ cassandra_config_dir }}/jvm.options mode=0664"

- name: Enable performance tweaks
  script: performance_tweaks.sh

- name: Enable config to replace existing dead node
  command: "sed -i -e '/cassandra.replace_address/s/#JVM_OPTS/JVM_OPTS/' {{ cassandra_config_dir }}/cassandra-env.sh"
  when:
    - replace_dead_server | default(false) | bool

- name: Disable auto_bootstrap for empty cluster
  command: "sed -i -e '/#auto_boostrap/s/#auto_boostrap/auto_boostrap/' {{ cassandra_config_dir }}/cassandra.yaml"
  when:
    - empty_cluster | default(false) | bool

- include_tasks: dse_config.yml
  when: install_version == "dse"

- name: Cassandra DCE startup
  service: name=cassandra state=restarted
  when: install_version == "dce"

- name: Cassandra DSE startup
  service: name=dse state=restarted
  when: install_version == "dse"

- name: Cassandra Apache startup
  service: name=cassandra state=restarted
  when: install_version == "apache"

- name: Wait for Cassandra startup (bootstrapping)
  wait_for: path=/var/log/cassandra/system.log search_regex="Starting listening for CQL clients" timeout=900
  when:
    - not (init_server | default(false) | bool)

- name: Wait for Cassandra startup (not bootstrapping)
  pause: seconds=180
  when:
    - init_server | default(false) | bool

- name: Disable config to replace existing dead node
  command: "sed -i -e '/cassandra.replace_address/s/JVM_OPTS=/#JVM_OPTS=/' {{ cassandra_config_dir }}/cassandra-env.sh"
  when:
    - replace_dead_server | default(false) | bool

- name: Re-enable auto_bootstrap for empty cluster
  command: "sed -i -e '/auto_boostrap/s/auto_boostrap/#auto_boostrap/' {{ cassandra_config_dir }}/cassandra.yaml"
  when:
    - empty_cluster | default(false) | bool

- name: Extract tokens & update cassandra.yaml
  script: token_store.sh
  when:
    - init_server | default(false) | bool

- name: Copy tokens from node
  fetch: "src={{ cassandra_config_dir }}/TOKENS dest=inventory/tokens/{{ ansible_hostname }}.token flat=yes"
  when:
    - init_server | default(false) | bool
